[2022-04-18 16:39:03,363] [log.py|__console] [line:38] INFO    : 当前执行测试用例ID-> test_login001.1 ; 测试点-> 用户名和密码为空登录
[2022-04-18 16:39:03,556] [log.py|__console] [line:38] INFO    : 当前执行测试用例ID-> test_login001.1 ; 测试点-> 用户名和密码为空登录
[2022-04-18 16:39:11,543] [log.py|__console] [line:38] INFO    : 检查点-> 请输入账户名
[2022-04-18 16:39:11,621] [log.py|__console] [line:38] INFO    : 异常登录，返回实际结果是->: 请输入账户名
[2022-04-18 16:39:11,745] [log.py|__console] [line:38] INFO    : 检查点-> 请输入账户名
[2022-04-18 16:39:11,849] [log.py|__console] [line:38] INFO    : 异常登录，返回实际结果是->: 请输入账户名
[2022-04-18 16:39:12,068] [log.py|__console] [line:38] INFO    : 当前执行测试用例ID-> test_login001.2 ; 测试点-> 用户名为空登录
[2022-04-18 16:39:12,330] [log.py|__console] [line:38] INFO    : 当前执行测试用例ID-> test_login001.2 ; 测试点-> 用户名为空登录
[2022-04-18 16:39:20,136] [log.py|__console] [line:38] INFO    : 检查点-> 请输入账户名
[2022-04-18 16:39:20,214] [log.py|__console] [line:38] INFO    : 异常登录，返回实际结果是->: 请输入账户名
[2022-04-18 16:39:20,300] [log.py|__console] [line:38] INFO    : 检查点-> 请输入账户名
[2022-04-18 16:39:20,381] [log.py|__console] [line:38] INFO    : 异常登录，返回实际结果是->: 请输入账户名
[2022-04-18 16:39:20,475] [log.py|__console] [line:38] INFO    : 当前执行测试用例ID-> test_login001.3 ; 测试点-> 密码为空登录
[2022-04-18 16:39:20,670] [log.py|__console] [line:38] INFO    : 当前执行测试用例ID-> test_login001.3 ; 测试点-> 密码为空登录
[2022-04-18 16:39:28,519] [log.py|__console] [line:38] INFO    : 检查点-> 请输入密码
[2022-04-18 16:39:28,597] [log.py|__console] [line:38] INFO    : 异常登录，返回实际结果是->: 请输入密码
[2022-04-18 16:39:28,706] [log.py|__console] [line:38] INFO    : 检查点-> 请输入密码
[2022-04-18 16:39:28,808] [log.py|__console] [line:38] INFO    : 异常登录，返回实际结果是->: 请输入密码
[2022-04-18 16:39:28,889] [log.py|__console] [line:38] INFO    : 当前执行测试用例ID-> test_login001.4 ; 测试点-> 用户名或密码不匹配
[2022-04-18 16:39:29,077] [log.py|__console] [line:38] INFO    : 当前执行测试用例ID-> test_login001.4 ; 测试点-> 用户名或密码不匹配
[2022-04-18 16:39:36,971] [log.py|__console] [line:38] INFO    : 检查点-> 用户名或密码错误
[2022-04-18 16:39:37,049] [log.py|__console] [line:38] INFO    : 异常登录，返回实际结果是->: 用户名或密码错误
[2022-04-18 16:39:37,112] [log.py|__console] [line:38] INFO    : 检查点-> 用户名或密码错误
[2022-04-18 16:39:37,190] [log.py|__console] [line:38] INFO    : 异常登录，返回实际结果是->: 用户名或密码错误
[2022-04-18 16:39:37,351] [log.py|__console] [line:38] INFO    : 当前执行测试用例ID-> test_login001.5 ; 测试点-> 用户名和密码正确
[2022-04-18 16:39:37,471] [log.py|__console] [line:38] INFO    : 当前执行测试用例ID-> test_login001.5 ; 测试点-> 用户名和密码正确
[2022-04-18 16:39:48,753] [log.py|__console] [line:38] INFO    : 检查点-> 退出
[2022-04-18 16:39:48,846] [log.py|__console] [line:38] INFO    : 成功登录，返回实际结果是->: 退出
[2022-04-18 16:39:50,604] [log.py|__console] [line:38] INFO    : 检查点-> 退出
[2022-04-18 16:39:50,698] [log.py|__console] [line:38] INFO    : 成功登录，返回实际结果是->: 退出
